python:
	python puzzle_24/puzzle.py

javascript:
	node puzzle_25/puzzle.js

rust:
	rustc puzzle_22/puzzle.rs -o build/puzzle_rs
	./build/puzzle_rs

r:
	Rscript puzzle_11/puzzle.r

julia:
	julia puzzle_20/puzzle.jl

ruby:
	ruby puzzle_17/puzzle.rb

c++:
	g++ puzzle_4/puzzle.cpp -o build/puzzle_cpp
	./build/puzzle_cpp

go:
	go run puzzle_18/puzzle.go

java:
	javac -d build/ puzzle_16/Puzzle.java
	cd build; java Puzzle

scala:
	scala puzzle_21/puzzle.scala

kotlin:
	kotlinc puzzle_19/puzzle.kt -include-runtime -d build/puzzle_kotlin.jar
	java -jar build/puzzle_kotlin.jar

perl:
	perl puzzle_9/puzzle.pl

typescript:
	cd puzzle_23; tsc puzzle.ts; node puzzle.js

lisp:
	sbcl --script puzzle_7/puzzle.lsp

elixir:
	elixir puzzle_8/puzzle.exs

clojure:
	clj puzzle_5/puzzle.clj

fsharp:
	dotnet fsi puzzle_3/puzzle.fsx

swift:
	swiftc -o build/puzzle_swift puzzle_12/puzzle.swift
	./build/puzzle_swift

erlang:
	erlc -o build puzzle_2/puzzle.erl
	cd build; erl
	# Run this in Erlang interpreter
	puzzle:solvePuzzles().

csharp:
	dotnet script puzzle_15/puzzle.cs

haskell:
	ghc -o build/puzzle_haskell puzzle_1/puzzle.hs
	./build/puzzle_haskell

dart:
	dart run puzzle_10/puzzle.dart

lua:
	lua puzzle_13/puzzle.lua

wren:
	wren_cli puzzle_14/puzzle.wren