python:
	python puzzle.py

javascript:
	node puzzle.js

rust:
	rustc puzzle.rs -o build/puzzle_rs
	./build/puzzle_rs

r:
	Rscript puzzle_11/puzzle.r

julia:
	julia puzzle.jl

ruby:
	ruby puzzle.rb

c++:
	g++ puzzle_4/puzzle.cpp -o build/puzzle_cpp
	./build/puzzle_cpp

c:
	gcc puzzle.c -o build/puzzle_c
	./build/puzzle_c

go:
	go run puzzle.go

java:
	javac -d build/ Puzzle.java
	cd build; java Puzzle

scala:
	scala puzzle.scala

kotlin:
	kotlinc puzzle.kt -include-runtime -d build/puzzle_kotlin.jar
	java -jar build/puzzle_kotlin.jar

perl:
	perl puzzle_9/puzzle.pl

typescript:
	tsc --outDir build puzzle.ts
	node build/puzzle.js

lisp:
	sbcl --script puzzle_7/puzzle.lsp

elixir:
	elixir puzzle_8/puzzle.exs

zig:
	./puzzle.zig

clojure:
	clj puzzle_5/puzzle.clj

fsharp:
	dotnet fsi puzzle_3/puzzle.fsx

swift:
	swiftc -o build/puzzle_swift puzzle_12/puzzle.swift
	./build/puzzle_swift

erlang:
	erlc -o build puzzle_2/puzzle.erl
	cd build; erl
	# Run this in Erlang interpreter
	puzzle:solvePuzzles().

csharp:
	dotnet script puzzle_15/puzzle.cs

haskell:
	ghc -o build/puzzle_haskell puzzle_1/puzzle.hs
	./build/puzzle_haskell

dart:
	dart run puzzle_10/puzzle.dart

lua:
	lua puzzle_13/puzzle.lua

wren:
	wren_cli puzzle_14/puzzle.wren