python:
	python puzzle.py

javascript:
	node puzzle.js

rust:
	rustc puzzle.rs -o build/puzzle_rs
	./build/puzzle_rs

r:
	Rscript puzzle.r

julia:
	julia puzzle.jl

ruby:
	ruby puzzle.rb

c++:
	g++ puzzle.cpp -o build/puzzle_cpp
	./build/puzzle_cpp

c:
	gcc puzzle.c -o build/puzzle_c
	./build/puzzle_c

go:
	go run puzzle.go

java:
	javac -d build/ Puzzle.java
	cd build; java Puzzle

scala:
	scala puzzle.scala

kotlin:
	kotlinc puzzle.kt -include-runtime -d build/puzzle_kotlin.jar
	java -jar build/puzzle_kotlin.jar

perl:
	perl puzzle.pl

typescript:
	tsc --outDir build puzzle.ts
	node build/puzzle.js

lisp:
	sbcl --script puzzle.lsp

elixir:
	elixir puzzle.exs

zig:
	./puzzle.zig

clojure:
	clj puzzle.clj

fsharp:
	dotnet fsi puzzle.fsx

swift:
	swiftc -o build/puzzle_swift puzzle.swift
	./build/puzzle_swift

erlang:
	erlc -o build puzzle.erl
	cd build; erl
	# Run this in Erlang interpreter
	puzzle:solve_puzzle().

csharp:
	dotnet script puzzle.cs

haskell:
	ghc -o build/puzzle_haskell puzzle.hs
	./build/puzzle_haskell

dart:
	dart run puzzle.dart